---
# ServiceMonitor to expose metrics for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-node-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nodeapp
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - path: /metrics
      port: "3000"
      interval: 15s
