---
- name: Install required dependencies
  apt:
    name:
      - curl
      - unzip
    state: present
    
- name: Download AWS CLI v2 installer
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0644'

- name: Unzip AWS CLI v2 installer
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Install AWS CLI v2
  ansible.builtin.shell:
    cmd: "/tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli"
    creates: "/usr/local/bin/aws"

- name: Clean up AWS CLI v2 installer files
  file:
    path: "/tmp/awscliv2.zip"
    state: absent

- name: Verify AWS CLI version
  command: aws --version
  register: aws_version
  changed_when: false

- name: Show AWS CLI version
  debug:
    var: aws_version.stdout
